# Generated by Django 3.2.10 on 2022-02-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ExpenseId', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
    ]
