# Generated by Django 4.0.2 on 2022-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last name')),
                ('business', models.CharField(max_length=100, verbose_name='Business Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
            ],
        ),
    ]
