# Generated by Django 3.2.10 on 2022-02-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
