# Generated by Django 3.2.10 on 2022-05-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_first_name_useraccount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
    ]
