# Generated by Django 3.2.10 on 2022-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('VendorId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Pan', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Bank', models.CharField(max_length=100)),
            ],
        ),
    ]
