# Generated by Django 3.2.10 on 2022-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Invoice_no', models.IntegerField()),
                ('Invoice_Date', models.DateField()),
                ('Payment_Date', models.DateField()),
                ('Amount', models.IntegerField()),
                ('Photo', models.CharField(max_length=100)),
            ],
        ),
    ]
