# Generated by Django 3.2.10 on 2022-02-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_auto_20220219_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Photo',
        ),
    ]
